
import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';

const translations = {
  en: {
    // General
    'getStarted': 'Get Started',
    'services': 'Services',
    'company': 'Company',
    'contactUs': 'Contact Us',
    'allRightsReserved': '© 2025 BookLingo. All rights reserved.',
    'backToHome': 'Back to Home',

    // Layout & Navigation
    'layout.nav.howItWorks': 'How It Works',
    'layout.nav.about': 'About',
    'home.nav.home': 'Home',

    // Home Page
    'home.hero.title': 'Professional Interpreters Platform',
    'home.hero.subtitle': 'BookLingo bridges language barriers by connecting you with professional interpreters for simultaneous, consecutive, and Online interpretation services.',
    'home.hero.book': 'Book an Interpreter',
    'home.hero.become': 'Become an Interpreter',
    'home.hero.interpretersCount': '30+ Professional Interpreters',
    'home.services.title': 'Professional Interpretation Services',
    'home.services.subtitle': 'Choose from our range of professional interpretation services tailored to your specific needs',
    'home.services.simultaneous': 'Simultaneous',
    'home.services.consecutive': 'Consecutive',
    'home.services.online': 'Online',
    'home.services.translation': 'Translation',
    'home.services.simultaneous.desc': 'Real-time interpretation for conferences, meetings, and large events with professional equipment setup.',
    'home.services.consecutive.desc': 'Speaker-pause interpretation perfect for business meetings, negotiations, and smaller gatherings.',
    'home.services.online.desc': 'Virtual interpretation services connecting interpreters and clients across any distance.',
    'home.how.title': 'How BookLingo Works',
    'home.how.subtitle': 'Get connected with professional interpreters in three simple steps',
    'home.how.step1.title': 'Submit Your Request',
    'home.how.step1.desc': 'Tell us about your interpretation needs, preferred languages, and event details',
    'home.how.step2.title': 'Get Matched',
    'home.how.step2.desc': 'Our AI matches you with qualified interpreters based on your requirements',
    'home.how.step3.title': 'Book & Connect',
    'home.how.step3.desc': 'Confirm your booking and connect with your assigned professional interpreter',
    'home.why.title': 'Why Choose BookLingo?',
    'home.why.subtitle': "We're committed to providing the highest quality interpretation services with unmatched reliability and professionalism.",
    'home.feature.professional': 'Professional Interpreters',
    'home.feature.professional.desc': 'Some interpreters are sworn interpreters for written translation',
    'home.feature.instant': 'Instant Booking',
    'home.feature.instant.desc': 'Book qualified interpreters in just a few clicks',
    'home.feature.support': '24/7 Support',
    'home.feature.support.desc': 'Round-the-clock customer support for all your needs',
    'home.cta.title': 'Ready to Break Language Barriers?',
    'home.cta.subtitle': 'Join thousands of satisfied clients who trust BookLingo for their professional interpretation needs.',
    'home.cta.button': 'Start Your Booking',
    'home.footer.tagline': 'Bridging language barriers with professional, reliable interpretation services worldwide.',
    'home.footer.aboutUs': 'About Us',
    'home.footer.pricing': 'Pricing',
    'home.footer.contact': 'Contact',
    'home.footer.address': 'Iskan Tower, Erbil, Iraq',

    // Auth Page
    'auth.welcome': 'Welcome to BookLingo',
    'auth.selectRole': 'Please select your role to continue',
    'auth.continueClient': 'Continue as Client',
    'auth.continueInterpreter': 'Continue as Interpreter',
    'auth.createClientAccount': 'Create client account',
    'auth.createInterpreterAccount': 'Create interpreter account',
    'auth.clientSignIn': 'Client Sign In',
    'auth.interpreterSignIn': 'Interpreter Sign In',
    'auth.toStartBooking': 'to start booking services',
    'auth.toAccessDashboard': 'to access your dashboard',
    'auth.email': 'Email',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': 'Password',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signUp': 'Sign Up',
    'auth.signIn': 'Sign In',
    'auth.alreadyHaveAccount': 'Already have an account? Sign In',
    'auth.needAccount': 'Need an account? Sign Up',
    'auth.or': 'OR',
    'auth.signInWithGoogle': 'Sign in with Google',
    'auth.googleSignInComingSoon': 'Google sign-in coming soon',
    'auth.simulatingSignUp': 'Simulating Sign Up for',
    'auth.simulatingSignIn': 'Simulating Sign In for',
    'auth.redirectingProfile': 'Redirecting to complete profile.',

    // Profile Page (Interpreter Focus)
    'profile.title': 'Complete Your Interpreter Profile',
    'profile.subtitle': "Provide your professional details to start receiving booking requests.",
    'profile.fullName': 'Full Name',
    'profile.fullNamePlaceholder': 'e.g., John Smith',
    'profile.phone': 'WhatsApp Number',
    'profile.phonePlaceholder': '+1 (555) 123-4567',
    'profile.email': 'Email Address',
    'profile.about.title': 'About Me',
    'profile.about.placeholder': 'Tell clients about your experience, qualifications, and areas of expertise.',
    'profile.experience': 'Years of Experience',
    'profile.experiencePlaceholder': 'e.g., 5',
    'profile.interpretationTypes': 'Interpretation Types',
    'profile.type.simultaneous': 'Simultaneous',
    'profile.type.consecutive': 'Consecutive',
    'profile.type.remote': 'Remote',
    'profile.languages.title': 'Spoken Languages',
    'profile.lang.en': 'English',
    'profile.lang.ar': 'Arabic',
    'profile.lang.ku_sorani': 'Kurdish (Sorani)',
    'profile.lang.ku_bahdini': 'Kurdish (Bahdini)',
    'profile.lang.tr': 'Turkish',
    'profile.lang.fr': 'French',
    'profile.lang.it': 'Italian',
    'profile.lang.other': 'Others',
    'profile.lang.otherPlaceholder': 'Specify other language',
    'profile.credentials.title': 'Credentials',
    'profile.credentials.sworn': 'Sworn Translator',
    'profile.credentials.swornId': 'Upload Sworn ID Card',
    'profile.credentials.accredited': 'Accredited Interpreter',
    'profile.credentials.accreditationCert': 'Upload Accreditation Certificate',
    'profile.credentials.uploadPlaceholder': 'Click to upload document',
    'profile.credentials.uploading': 'Uploading...',
    'profile.credentials.uploaded': 'File Uploaded: ',
    'profile.rates.title': 'Rates & Payment',
    'profile.rates.currency': 'Currency',
    'profile.rates.rate': 'Hourly Rate',
    'profile.rates.ratePlaceholder': 'e.g., 100',
    'profile.rates.paymentTerms': 'Payment Terms',
    'profile.rates.paymentTermsPlaceholder': 'e.g., Payment due within 14 days of service completion.',
    'profile.rates.bankInfo': 'Bank Information (Optional)',
    'profile.rates.bankName': 'Bank Name',
    'profile.rates.accountHolder': 'Account Holder Name',
    'profile.rates.iban': 'IBAN',
    'profile.save': 'Save My Profile',
    'profile.saving': 'Saving...',
    'profile.saveSuccess': 'Profile saved successfully!',

    // Dashboard Page
    'dashboard.client.title': 'Client Dashboard',
    'dashboard.interpreter.title': 'Interpreter Dashboard',
    'dashboard.welcome': 'Welcome back, {name}!',
    'dashboard.client.subtitle': 'Ready to book your next interpretation service?',
    'dashboard.interpreter.subtitle': 'Manage your bookings and grow your interpretation business.',
    'dashboard.client.bookTitle': 'Book an Interpreter',
    'dashboard.client.bookSubtitle': 'Find and book professional interpreters for your events',
    'dashboard.client.typeSimultaneous': 'Simultaneous',
    'dashboard.client.typeSimultaneousDesc': 'Real-time interpretation',
    'dashboard.client.typeConsecutive': 'Consecutive',
    'dashboard.client.typeConsecutiveDesc': 'Speaker-pause format',
    'dashboard.client.typeRemote': 'Remote',
    'dashboard.client.typeRemoteDesc': 'Virtual interpretation',
    'dashboard.client.newBookingButton': 'Start New Booking',
    'dashboard.client.recentBookingsTitle': 'Recent Bookings',
    'dashboard.client.totalLabel': 'Total',
    'dashboard.client.bookingStatus.completed': 'Completed',
    'dashboard.client.bookingStatus.confirmed': 'Confirmed',
    'dashboard.interpreter.profileStatusTitle': 'Profile Status',
    'dashboard.interpreter.profileStatusComplete': '{percent}% Complete',
    'dashboard.interpreter.profileStatusDesc': 'Complete your profile to start receiving booking requests from clients.',
    'dashboard.interpreter.editProfileButton': 'Create/Edit Profile',
    'dashboard.interpreter.bookings.title': 'My Bookings',
    'dashboard.interpreter.calendar.title': 'My Availability',
    'dashboard.interpreter.calendar.booked': 'Booked',
    'dashboard.interpreter.noBookingsTitle': 'No upcoming bookings',
    'dashboard.interpreter.noBookingsDesc': 'Once your profile is complete, clients will be able to book your services.',
    'dashboard.interpreter.viewRequestsButton': 'View All Requests',
    'dashboard.interpreter.updateAvailabilityButton': 'Update Availability',
    'dashboard.interpreter.stats.rating': 'Average Rating',
    'dashboard.interpreter.stats.jobs': 'Jobs Completed',
    'dashboard.interpreter.stats.hours': 'Hours Interpreted',
    'dashboard.booking.notification.title': 'New Booking Simulation',
    'dashboard.booking.notification.desc': 'Click to simulate a new client booking for testing purposes.',
    'dashboard.booking.notification.button': 'Simulate New Booking',
    'dashboard.booking.notification.whatsapp_en': 'New Booking Request for {date}. Check your dashboard for details.',
    'dashboard.booking.notification.whatsapp_ar': 'طلب حجز جديد للتواريخ {date}. يرجى مراجعة لوحة التحكم للتفاصيل.',

    // Find Interpreters Page
    'findInterpreters.backToDashboard': 'Back to Dashboard',
    'findInterpreters.title': 'Find Professional Interpreters',
    'findInterpreters.subtitle': 'Browse and book qualified interpreters for your events',
    'findInterpreters.available': 'Available',
    'findInterpreters.loading': 'Loading interpreters...',
    'findInterpreters.searchPlaceholder': 'Search by name, language, or specialty...',
    'findInterpreters.filterLanguage': 'Filter by Language',
    'findInterpreters.filterSpecialty': 'Filter by Specialty',
    'findInterpreters.allLanguages': 'All Languages',
    'findInterpreters.allSpecialties': 'All Specialties',
    'findInterpreters.searchLabel': 'Search:',
    'findInterpreters.languageLabel': 'Language:',
    'findInterpreters.specialtyLabel': 'Specialty:',
    'findInterpreters.noInterpretersTitle': 'No interpreters found',
    'findInterpreters.noInterpretersDesc': 'Try adjusting your search criteria or filters',

    // Interpreter Card
    'interpreterCard.languages': 'Languages:',
    'interpreterCard.specialties': 'Specialties:',
    'interpreterCard.moreLanguages': '+{count} more',
    'interpreterCard.yearsExperience': '{years}+ years experience',
    'interpreterCard.sworn': 'Sworn',

    // Booking Modal
    'bookingModal.title': 'Book Interpretation Service',
    'bookingModal.clientInfoTitle': 'Client Information',
    'bookingModal.clientName': 'Full name or company/organization name',
    'bookingModal.clientNamePlaceholder': 'Your Name or Company',
    'bookingModal.email': 'Email Address',
    'bookingModal.emailPlaceholder': 'you@example.com',
    'bookingModal.mobile': 'Mobile number',
    'bookingModal.mobilePlaceholder': '+964 XXX XXX XXXX',
    'bookingModal.required': '*',
    'bookingModal.serviceSelectionTitle': 'Service Selection',
    'bookingModal.serviceType': 'Select Interpretation Type',
    'bookingModal.serviceTypePlaceholder': 'Choose service type',
    'bookingModal.simultaneousService': 'Simultaneous Interpretation - Full workday: 2 to 8 hours',
    'bookingModal.consecutiveService': 'Consecutive Interpretation',
    'bookingModal.onlineService': 'Online Interpretation',
    'bookingModal.notesLabel': 'Location, preferred time, and any other notes...',
    'bookingModal.notesPlaceholder': 'Provide details about the event, location, start time, duration, and any special requirements.',
    'bookingModal.calendarTitle': 'Select Dates',
    'bookingModal.selectedDates': 'Selected Dates:',
    'bookingModal.calendarLegend.selected': 'Selected',
    'bookingModal.calendarLegend.booked': 'Booked',
    'bookingModal.calendarLegend.available': 'Available',
    'bookingModal.cancel': 'Cancel',
    'bookingModal.bookViaWhatsApp': 'Book via WhatsApp',
    'bookingModal.rating': 'Rating:',
    'bookingModal.languages': 'Languages:',
    'bookingModal.specialties': 'Specialties:',
    'bookingModal.sworn': 'Sworn',
    'bookingModal.validationError': 'Please fill in all required fields and select at least one date.',
    'bookingModal.whatsappMessage': 'Hello! I\'d like to book interpretation services with {interpreterName}.\n\nDetails:\n- Service: {serviceName} ({servicePrice})\n- Dates: {selectedDates}\n- Client: {clientName}\n- Phone: {mobile}\n- Email: {email}\n{notes}\n\nLooking forward to working with you!',
    'bookingModal.additionalNotes': '\n- Additional notes: {notes}',

    // Simultaneous Page
    'simultaneous.badge': 'Professional Service',
    'simultaneous.title': 'Simultaneous Interpretation',
    'simultaneous.subtitle': 'Real-time interpretation services for conferences, meetings, and large-scale events with professional interpreters and state-of-the-art equipment.',
    'simultaneous.bookButton': 'Book Simultaneous Interpreter',
    'simultaneous.benefit1.title': 'Real-Time Translation',
    'simultaneous.benefit1.desc': 'Instant interpretation without delays or pauses in conversation',
    'simultaneous.benefit2.title': 'Large Events',
    'simultaneous.benefit2.desc': 'Perfect for conferences, seminars, and international meetings',
    'simultaneous.benefit3.title': 'Professional Equipment',
    'simultaneous.benefit3.desc': 'State-of-the-art audio equipment and soundproof booths',
    'simultaneous.how.title': 'How It Works',
    'simultaneous.how.step1': 'Professional interpreters work in soundproof booths',
    'simultaneous.how.step2': 'Real-time interpretation delivered through headsets',
    'simultaneous.how.step3': 'Suitable for multilingual events and conferences',
    'simultaneous.cta.title': 'Ready to Book Your Simultaneous Interpreter?',
    'simultaneous.cta.button': 'Get Started Now',

    // Consecutive Page
    'consecutive.badge': 'Conversational Service',
    'consecutive.title': 'Consecutive Interpretation',
    'consecutive.subtitle': 'Speaker-pause interpretation perfect for business meetings, legal consultations, and smaller gatherings where natural conversation flow is essential.',
    'consecutive.bookButton': 'Book Consecutive Interpreter',
    'consecutive.benefit1.title': 'Natural Flow',
    'consecutive.benefit1.desc': 'Allows for natural conversation rhythm and speaker interaction',
    'consecutive.benefit2.title': 'Small Groups',
    'consecutive.benefit2.desc': 'Ideal for business meetings, negotiations, and consultations',
    'consecutive.benefit3.title': 'Personal Touch',
    'consecutive.benefit3.desc': 'Direct interaction between all parties with professional mediation',
    'consecutive.perfectFor.title': 'Perfect For',
    'consecutive.perfectFor.item1': 'Business negotiations and meetings',
    'consecutive.perfectFor.item2': 'Legal consultations and depositions',
    'consecutive.perfectFor.item3': 'Medical appointments and consultations',
    'consecutive.perfectFor.item4': 'Court proceedings and hearings',
    'consecutive.perfectFor.item5': 'Training sessions and workshops',
    'consecutive.perfectFor.item6': 'One-on-one interviews and consultations',
    'consecutive.cta.title': 'Need a Consecutive Interpreter?',
    'consecutive.cta.button': 'Book Your Session',

    // Remote Page
    'remote.badge': 'Virtual Service',
    'remote.title': 'Remote Interpretation',
    'remote.subtitle': 'Virtual interpretation services connecting interpreters and clients across any distance. Perfect for online meetings, webinars, and digital conferences.',
    'remote.bookButton': 'Book Remote Interpreter',
    'remote.benefit1.title': 'Global Access',
    'remote.benefit1.desc': 'Connect with interpreters worldwide from anywhere',
    'remote.benefit2.title': '24/7 Availability',
    'remote.benefit2.desc': 'Round-the-clock service across all time zones',
    'remote.benefit3.title': 'Cost Effective',
    'remote.benefit3.desc': 'No travel costs or venue requirements needed',
    'remote.requirements.title': 'Technical Requirements',
    'remote.requirements.basic.title': 'Basic Requirements',
    'remote.requirements.basic.item1': 'Stable internet connection (minimum 10 Mbps)',
    'remote.requirements.basic.item2': 'Computer or tablet with camera and microphone',
    'remote.requirements.basic.item3': 'Quiet environment for clear audio',
    'remote.requirements.basic.item4': 'Compatible web browser or app',
    'remote.requirements.platform.title': 'Platform Support',
    'remote.requirements.platform.item1': 'Zoom, Microsoft Teams, Google Meet',
    'remote.requirements.platform.item2': 'WebEx, GoToMeeting integration',
    'remote.requirements.platform.item3': 'Custom interpretation platforms',
    'remote.requirements.platform.item4': 'Phone-based interpretation available',
    'remote.cta.title': 'Ready for Virtual Interpretation?',
    'remote.cta.button': 'Start Remote Session',

    // Translation Page
    'translation.badge': 'Translation Service',
    'translation.title': 'Document Translation',
    'translation.subtitle': 'Professional document translation services with certified translators. Fast, accurate, and confidential translation for all your business and legal needs.',
    'translation.bookButton': 'Get Translation Quote',
    'translation.service1.title': 'Legal Documents',
    'translation.service1.desc': 'Contracts, court documents, and legal correspondence',
    'translation.service2.title': 'Certified Translations',
    'translation.service2.desc': 'Official translations with certification for legal use',
    'translation.service3.title': 'Confidential & Secure',
    'translation.service3.desc': 'Strict confidentiality protocols for sensitive documents',
    'translation.types.title': 'Document Types We Handle',
    'translation.types.item1': 'Legal contracts and agreements',
    'translation.types.item2': 'Medical records and reports',
    'translation.types.item3': 'Academic transcripts and diplomas',
    'translation.types.item4': 'Immigration documents and forms',
    'translation.types.item5': 'Technical manuals and specifications',
    'translation.types.item6': 'Financial statements and reports',
    'translation.types.item7': 'Marketing materials and websites',
    'translation.types.item8': 'Personal documents (birth certificates, etc.)',
    'translation.turnaround.title': 'Fast Turnaround',
    'translation.turnaround.item1': '• Express service: 24-48 hours',
    'translation.turnaround.item2': '• Standard service: 3-5 business days',
    'translation.turnaround.item3': '• Large documents: Custom timeline',
    'translation.turnaround.item4': '• Rush jobs available with surcharge',
    'translation.process.title': 'Easy Process',
    'translation.process.item1': '• Upload documents securely online',
    'translation.process.item2': '• Get instant quote and timeline',
    'translation.process.item3': '• Professional translation by experts',
    'translation.process.item4': '• Quality review and delivery',
    'translation.cta.title': 'Need Document Translation?',
    'translation.cta.button': 'Upload Documents Now',

    // About Page
    'about.badge': 'About BookLingo',
    'about.title': 'Breaking Language Barriers Worldwide',
    'about.subtitle': 'Founded with the mission to make professional interpretation services accessible to everyone, BookLingo connects clients with certified interpreters across the globe.',
    'about.stat.clients': 'Satisfied Clients',
    'about.stat.interpreters': 'Professional Simultaneous Interpreters',
    'about.stat.languages': 'Languages Supported',
    'about.stat.reliability': 'Sworn Interpreters',
    'about.story.title': 'Our Story',
    'about.story.p1': 'BookLingo was born from a simple yet powerful vision: to eliminate language barriers that prevent meaningful communication in our increasingly connected world.',
    'about.story.p2': 'Founded by a team of language professionals and tech innovators, we recognized the growing need for reliable, professional interpretation services that could adapt to the modern business landscape.',
    'about.story.p3': "Today, we're proud to serve thousands of clients worldwide, from multinational corporations to individual entrepreneurs, helping them communicate effectively across languages and cultures.",
    'about.values.title': 'Our Values',
    'about.value1.title': 'Excellence',
    'about.value1.desc': 'We maintain the highest standards in interpretation services through rigorous vetting and continuous training.',
    'about.value2.title': 'Trust',
    'about.value2.desc': 'Building lasting relationships with clients and interpreters through transparency and reliability.',
    'about.value3.title': 'Innovation',
    'about.value3.desc': 'Leveraging technology to make professional interpretation services more accessible worldwide.',
    'about.mission.title': 'Our Mission',
    'about.mission.desc': 'To empower global communication by providing accessible, reliable, and professional interpretation services that bridge language gaps and foster understanding across cultures, enabling businesses and individuals to thrive in our interconnected world.',
    'about.cta.title': 'Ready to Experience Professional Interpretation?',
    'about.cta.button': 'Get Started Today',

    // Pricing Page
    'pricing.badge': 'Transparent Pricing',
    'pricing.title': 'Choose Your Interpretation Plan',
    'pricing.subtitle': 'Professional interpretation services with transparent pricing. No hidden fees, no surprises - just exceptional service at fair rates.',
    'pricing.plan.basic.name': 'Basic',
    'pricing.plan.basic.desc': 'Perfect for small meetings and consultations',
    'pricing.plan.basic.feature1': 'Consecutive interpretation',
    'pricing.plan.basic.feature2': 'Up to 2 hours per session',
    'pricing.plan.basic.feature3': 'Phone and video support',
    'pricing.plan.basic.feature4': '24-hour advance booking',
    'pricing.plan.basic.feature5': 'Basic language pairs',
    'pricing.plan.basic.button': 'Contact Sales',
    'pricing.plan.pro.name': 'Professional',
    'pricing.plan.pro.desc': 'Ideal for business meetings and conferences',
    'pricing.plan.pro.feature1': 'Simultaneous & consecutive',
    'pricing.plan.pro.feature2': 'Extended session duration',
    'pricing.plan.pro.feature3': 'Professional equipment included',
    'pricing.plan.pro.feature4': 'Same-day booking available',
    'pricing.plan.pro.feature5': '50+ language pairs',
    'pricing.plan.pro.feature6': 'Dedicated account manager',
    'pricing.plan.pro.badge': 'Most Popular',
    'pricing.plan.pro.button': 'Contact Sales',
    'pricing.plan.enterprise.name': 'Enterprise',
    'pricing.plan.enterprise.desc': 'Tailored solutions for large organizations',
    'pricing.plan.enterprise.feature1': 'All interpretation services',
    'pricing.plan.enterprise.feature2': 'Unlimited session duration',
    'pricing.plan.enterprise.feature3': 'On-site equipment setup',
    'pricing.plan.enterprise.feature4': 'Emergency booking (2-hour notice)',
    'pricing.plan.enterprise.feature5': 'All languages supported',
    'pricing.plan.enterprise.feature6': 'Dedicated team assignment',
    'pricing.plan.enterprise.feature7': 'Volume discounts',
    'pricing.plan.enterprise.feature8': '24/7 priority support',
    'pricing.plan.enterprise.badge': 'Best Value',
    'pricing.plan.enterprise.button': 'Contact Sales',
    'pricing.additional.title': 'Additional Services',
    'pricing.additional.subtitle': 'Enhance your interpretation experience with our supplementary services',
    'pricing.additional.service1.name': 'Document Translation',
    'pricing.additional.service1.feature1': 'Certified translations',
    'pricing.additional.service1.feature2': '24-48 hour turnaround',
    'pricing.additional.service1.feature3': 'Legal document support',
    'pricing.additional.service2.name': 'Equipment Rental',
    'pricing.additional.service2.feature1': 'Wireless headsets',
    'pricing.additional.service2.feature2': 'Interpreter booths',
    'pricing.additional.service2.feature3': 'Audio systems',
    'pricing.additional.service3.name': 'Remote Setup Support',
    'pricing.additional.service3.feature1': 'Technical assistance',
    'pricing.additional.service3.feature2': 'Platform integration',
    'pricing.additional.service3.feature3': 'Testing session',
    'pricing.cta.title': 'Ready to Get Started?',
    'pricing.cta.subtitle': 'Book your first interpretation session and experience professional service at competitive rates.',
    'pricing.cta.button': 'Book Now',

    // Contact Page
    'contact.title': 'Send Us a Message',
    'contact.subtitle': "Fill out the form below and we'll get back to you shortly.",
    'contact.name.label': 'Full Name',
    'contact.name.placeholder': 'John Doe',
    'contact.email.label': 'Email Address',
    'contact.email.placeholder': 'john@company.com',
    'contact.phone.label': 'Phone Number',
    'contact.phone.placeholder': '+1 (555) 123-4567',
    'contact.subject.label': 'Subject',
    'contact.subject.placeholder': 'Interpretation services inquiry',
    'contact.message.label': 'Message',
    'contact.message.placeholder': 'Tell us about your interpretation needs, event details, languages required, etc.',
    'contact.button': 'Send Message',
    'contact.alert': "Thank you for your message! We'll get back to you within 24 hours.",

    // Interpreter Public Profile Page
    'interpreterProfile.bookTitle': 'Book This Interpreter',
    'interpreterProfile.bookSubtitle': 'Complete the form to send a booking request via WhatsApp.',
    'interpreterProfile.clientName': 'Client Full Name/Company',
    'interpreterProfile.clientNamePlaceholder': 'Your Name or Company',
    'interpreterProfile.mobile': 'Mobile Number',
    'interpreterProfile.mobilePlaceholder': 'e.g., 07801234567',
    'interpreterProfile.email': 'Email Address',
    'interpreterProfile.emailPlaceholder': 'you@example.com',
    'interpreterProfile.type': 'Interpretation Type',
    'interpreterProfile.simultaneousOption': 'Simultaneous - IQD 300,000/hour',
    'interpreterProfile.consecutiveOption': 'Consecutive - IQD 250,000/hour',
    'interpreterProfile.date': 'Select Date',
    'interpreterProfile.datePlaceholder': 'Pick a date',
    'interpreterProfile.notes': 'Location / Time / Notes',
    'interpreterProfile.notesPlaceholder': 'Provide details about the event, location, start time, duration, and any special requirements.',
    'interpreterProfile.bookButton': 'Book via WhatsApp',
    'interpreterProfile.aboutTitle': 'About the Interpreter',
    'interpreterProfile.experience': 'of experience',
    'interpreterProfile.viewCv': 'View CV',
    'interpreterProfile.galleryTitle': 'Work Gallery',
    'interpreterProfile.recommendationsTitle': 'Recommendation Letters',
    'interpreterProfile.paymentTitle': 'Payment',
    'interpreterProfile.paymentDesc': 'Payment is made in cash, in Iraqi Dinar (IQD), directly to the interpreter after the service is delivered.',
  },
  ar: {
    // General
    'getStarted': 'ابدأ الآن',
    'services': 'الخدمات',
    'company': 'الشركة',
    'contactUs': 'اتصل بنا',
    'allRightsReserved': '© 2025 بوك لينغو. جميع الحقوق محفوظة.',
    'backToHome': 'العودة إلى الرئيسية',

    // Layout & Navigation
    'layout.nav.howItWorks': 'كيف نعمل',
    'layout.nav.about': 'من نحن',
    'home.nav.home': 'الرئيسية',

    // Home Page
    'home.hero.title': 'منصة المترجمين المحترفين',
    'home.hero.subtitle': 'بوك لينغو يكسر حواجز اللغة عبر ربطك بمترجمين محترفين لخدمات الترجمة الفورية والتتبعية وعبر الإنترنت.',
    'home.hero.book': 'احجز مترجماً',
    'home.hero.become': 'كن مترجماً',
    'home.hero.interpretersCount': '+30 مترجم محترف',
    'home.services.title': 'خدمات الترجمة الاحترافية',
    'home.services.subtitle': 'اختر من بين مجموعتنا من خدمات الترجمة الاحترافية المصممة خصيصًا لاحتياجاتك',
    'home.services.simultaneous': 'الفورية',
    'home.services.consecutive': 'التتبعية',
    'home.services.online': 'عبر الإنترنت',
    'home.services.translation': 'الترجمة التحريرية',
    'home.services.simultaneous.desc': 'ترجمة فورية للمؤتمرات والاجتماعات والفعاليات الكبيرة مع إعداد المعدات الاحترافية.',
    'home.services.consecutive.desc': 'ترجمة تعتمد على توقف المتحدث، مثالية لاجتماعات العمل والمفاوضات والتجمعات الصغيرة.',
    'home.services.online.desc': 'خدمات ترجمة افتراضية تربط المترجمين والعملاء عبر أي مسافة.',
    'home.how.title': 'كيف يعمل بوك لينغو',
    'home.how.subtitle': 'تواصل مع مترجمين محترفين في ثلاث خطوات بسيطة',
    'home.how.step1.title': 'أرسل طلبك',
    'home.how.step1.desc': 'أخبرنا عن احتياجات الترجمة الخاصة بك واللغات المفضلة وتفاصيل الحدث',
    'home.how.step2.title': 'احصل على مرشحين',
    'home.how.step2.desc': 'يقوم نظامنا الذكي بمطابقتك مع مترجمين مؤهلين بناءً على متطلباتك',
    'home.how.step3.title': 'احجز وتواصل',
    'home.how.step3.desc': 'قم بتأكيد حجزك وتواصل مع المترجم المحترف الذي تم تعيينه لك',
    'home.why.title': 'لماذا تختار بوك لينغو؟',
    'home.why.subtitle': 'نحن ملتزمون بتقديم خدمات ترجمة عالية الجودة بموثوقية واحترافية لا مثيل لهما.',
    'home.feature.professional': 'مترجمون محترفون',
    'home.feature.professional.desc': 'بعض المترجمين محلفون للترجمة التحريرية',
    'home.feature.instant': 'حجز فوري',
    'home.feature.instant.desc': 'احجز مترجمين مؤهلين ببضع نقرات فقط',
    'home.feature.support': 'دعم على مدار الساعة',
    'home.feature.support.desc': 'دعم عملاء على مدار الساعة لجميع احتياجاتك',
    'home.cta.title': 'هل أنت مستعد لكسر حواجز اللغة؟',
    'home.cta.subtitle': 'انضم إلى آلاف العملاء الراضين الذين يثقون في بوك لينغو لتلبية احتياجاتهم من الترجمة الاحترافية.',
    'home.cta.button': 'ابدأ الحجز',
    'home.footer.tagline': 'كسر حواجز اللغة بخدمات ترجمة احترافية وموثوقة في جميع أنحاء العالم.',
    'home.footer.aboutUs': 'من نحن',
    'home.footer.pricing': 'الأسعار',
    'home.footer.contact': 'اتصل بنا',
    'home.footer.address': ' إسكان تاور، أربيل، العراق',

    // Auth Page
    'auth.welcome': 'أهلاً بك في بوك لينغو',
    'auth.selectRole': 'الرجاء تحديد دورك للمتابعة',
    'auth.continueClient': 'المتابعة كعميل',
    'auth.continueInterpreter': 'المتابعة كمترجم',
    'auth.createClientAccount': 'إنشاء حساب عميل',
    'auth.createInterpreterAccount': 'إنشاء حساب مترجم',
    'auth.clientSignIn': 'تسجيل دخول العميل',
    'auth.interpreterSignIn': 'تسجيل دخول المترجم',
    'auth.toStartBooking': 'لبدء حجز الخدمات',
    'auth.toAccessDashboard': 'للوصول إلى لوحة التحكم الخاصة بك',
    'auth.email': 'البريد الإلكتروني',
    'auth.emailPlaceholder': 'you@example.com',
    'auth.password': 'كلمة المرور',
    'auth.passwordPlaceholder': '••••••••',
    'auth.signUp': 'إنشاء حساب',
    'auth.signIn': 'تسجيل الدخول',
    'auth.alreadyHaveAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
    'auth.needAccount': 'تحتاج إلى حساب؟ إنشاء حساب',
    'auth.or': 'أو',
    'auth.signInWithGoogle': 'تسجيل الدخول باستخدام جوجل',
    'auth.googleSignInComingSoon': 'تسجيل الدخول عبر جوجل قريباً',
    'auth.simulatingSignUp': 'محاكاة إنشاء حساب لـ',
    'auth.simulatingSignIn': 'محاكاة تسجيل الدخول لـ',
    'auth.redirectingProfile': 'جارٍ التوجيه لإكمال الملف الشخصي.',

    // Profile Page (Interpreter Focus)
    'profile.title': 'أكمل ملفك كمترجم',
    'profile.subtitle': 'قدّم تفاصيلك المهنية لبدء تلقي طلبات الحجز.',
    'profile.fullName': 'الاسم الكامل',
    'profile.fullNamePlaceholder': 'مثال: جون سميث',
    'profile.phone': 'رقم الواتساب',
    'profile.phonePlaceholder': '+964 (XXX) XXX-XXXX',
    'profile.email': 'عنوان البريد الإلكتروني',
    'profile.about.title': 'عني',
    'profile.about.placeholder': 'أخبر العملاء عن خبرتك ومؤهلاتك ومجالات تخصصك.',
    'profile.experience': 'سنوات الخبرة',
    'profile.experiencePlaceholder': 'مثال: 5',
    'profile.interpretationTypes': 'أنواع الترجمة',
    'profile.type.simultaneous': 'فورية',
    'profile.type.consecutive': 'تتبعية',
    'profile.type.remote': 'عن بعد',
    'profile.languages.title': 'اللغات التي تتقنها',
    'profile.lang.en': 'الإنجليزية',
    'profile.lang.ar': 'العربية',
    'profile.lang.ku_sorani': 'الكردية (السورانية)',
    'profile.lang.ku_bahdini': 'الكردية (البهدينية)',
    'profile.lang.tr': 'التركية',
    'profile.lang.fr': 'الفرنسية',
    'profile.lang.it': 'الإيطالية',
    'profile.lang.other': 'أخرى',
    'profile.lang.otherPlaceholder': 'حدد اللغة الأخرى',
    'profile.credentials.title': 'المؤهلات',
    'profile.credentials.sworn': 'مترجم محلف',
    'profile.credentials.swornId': 'تحميل هوية المترجم المحلف',
    'profile.credentials.accredited': 'مترجم معتمد',
    'profile.credentials.accreditationCert': 'تحميل شهادة الاعتماد',
    'profile.credentials.uploadPlaceholder': 'انقر لتحميل المستند',
    'profile.credentials.uploading': 'جاري التحميل...',
    'profile.credentials.uploaded': 'تم تحميل الملف: ',
    'profile.rates.title': 'الأسعار والدفع',
    'profile.rates.currency': 'العملة',
    'profile.rates.rate': 'السعر للساعة',
    'profile.rates.ratePlaceholder': 'مثال: 100',
    'profile.rates.paymentTerms': 'شروط الدفع',
    'profile.rates.paymentTermsPlaceholder': 'مثال: الدفع مستحق خلال 14 يومًا من إتمام الخدمة.',
    'profile.rates.bankInfo': 'معلومات البنك (اختياري)',
    'profile.rates.bankName': 'اسم البنك',
    'profile.rates.accountHolder': 'اسم صاحب الحساب',
    'profile.rates.iban': 'IBAN',
    'profile.save': 'حفظ ملفي الشخصي',
    'profile.saving': 'جاري الحفظ...',
    'profile.saveSuccess': 'تم حفظ الملف الشخصي بنجاح!',

    // Dashboard Page
    'dashboard.client.title': 'لوحة تحكم العميل',
    'dashboard.interpreter.title': 'لوحة تحكم المترجم',
    'dashboard.welcome': 'أهلاً بعودتك، {name}!',
    'dashboard.client.subtitle': 'هل أنت مستعد لحجز خدمة الترجمة التالية؟',
    'dashboard.interpreter.subtitle': 'قم بإدارة حجوزاتك وتنمية أعمال الترجمة الخاصة بك.',
    'dashboard.client.bookTitle': 'احجز مترجماً',
    'dashboard.client.bookSubtitle': 'ابحث واحجز مترجمين محترفين لفعالياتك',
    'dashboard.client.typeSimultaneous': 'فورية',
    'dashboard.client.typeSimultaneousDesc': 'ترجمة في الوقت الفعلي',
    'dashboard.client.typeConsecutive': 'تتبعية',
    'dashboard.client.typeConsecutiveDesc': 'تنسيق وقفة المتحدث',
    'dashboard.client.typeRemote': 'عن بعد',
    'dashboard.client.typeRemoteDesc': 'ترجمة افتراضية',
    'dashboard.client.newBookingButton': 'ابدأ حجزاً جديداً',
    'dashboard.client.recentBookingsTitle': 'الحجوزات الأخيرة',
    'dashboard.client.totalLabel': 'الإجمالي',
    'dashboard.client.bookingStatus.completed': 'مكتمل',
    'dashboard.client.bookingStatus.confirmed': 'مؤكد',
    'dashboard.interpreter.profileStatusTitle': 'حالة الملف الشخصي',
    'dashboard.interpreter.profileStatusComplete': '{percent}% مكتمل',
    'dashboard.interpreter.profileStatusDesc': 'أكمل ملفك الشخصي لبدء تلقي طلبات الحجز من العملاء.',
    'dashboard.interpreter.editProfileButton': 'إنشاء/تعديل الملف الشخصي',
    'dashboard.interpreter.bookings.title': 'حجوزاتي',
    'dashboard.interpreter.calendar.title': 'مدى توفري',
    'dashboard.interpreter.calendar.booked': 'محجوز',
    'dashboard.interpreter.noBookingsTitle': 'لا توجد حجوزات قادمة',
    'dashboard.interpreter.noBookingsDesc': 'بمجرد اكتمال ملفك الشخصي، سيتمكن العملاء من حجز خدماتك.',
    'dashboard.interpreter.viewRequestsButton': 'عرض جميع الطلبات',
    'dashboard.interpreter.updateAvailabilityButton': 'تحديث التوفر',
    'dashboard.interpreter.stats.rating': 'متوسط التقييم',
    'dashboard.interpreter.stats.jobs': 'الوظائف المنجزة',
    'dashboard.interpreter.stats.hours': 'ساعات الترجمة',
    'dashboard.booking.notification.title': 'محاكاة حجز جديد',
    'dashboard.booking.notification.desc': 'انقر لمحاكاة حجز عميل جديد لأغراض الاختبار.',
    'dashboard.booking.notification.button': 'محاكاة حجز جديد',
    'dashboard.booking.notification.whatsapp_en': 'New Booking Request for {date}. Check your dashboard for details.',
    'dashboard.booking.notification.whatsapp_ar': 'طلب حجز جديد للتواريخ {date}. يرجى مراجعة لوحة التحكم للتفاصيل.',

    // Find Interpreters Page (Arabic)
    'findInterpreters.backToDashboard': 'العودة إلى لوحة التحكم',
    'findInterpreters.title': 'ابحث عن مترجمين محترفين',
    'findInterpreters.subtitle': 'تصفح واحجز مترجمين مؤهلين لفعالياتك',
    'findInterpreters.available': 'متاح',
    'findInterpreters.loading': 'جاري تحميل المترجمين...',
    'findInterpreters.searchPlaceholder': 'البحث بالاسم أو اللغة أو التخصص...',
    'findInterpreters.filterLanguage': 'تصفية حسب اللغة',
    'findInterpreters.filterSpecialty': 'تصفية حسب التخصص',
    'findInterpreters.allLanguages': 'جميع اللغات',
    'findInterpreters.allSpecialties': 'جميع التخصصات',
    'findInterpreters.searchLabel': 'بحث:',
    'findInterpreters.languageLabel': 'اللغة:',
    'findInterpreters.specialtyLabel': 'التخصص:',
    'findInterpreters.noInterpretersTitle': 'لم يتم العثور على مترجمين',
    'findInterpreters.noInterpretersDesc': 'حاول تعديل معايير البحث أو المرشحات',

    // Interpreter Card (Arabic)
    'interpreterCard.languages': 'اللغات:',
    'interpreterCard.specialties': 'التخصصات:',
    'interpreterCard.moreLanguages': '+{count} أكثر',
    'interpreterCard.yearsExperience': '+{years} سنوات خبرة',
    'interpreterCard.sworn': 'محلف',

    // Booking Modal (Arabic)
    'bookingModal.title': 'حجز خدمة الترجمة',
    'bookingModal.clientInfoTitle': 'معلومات العميل',
    'bookingModal.clientName': 'الاسم الكامل أو اسم الشركة/المنظمة',
    'bookingModal.clientNamePlaceholder': 'اسمك أو اسم شركتك',
    'bookingModal.email': 'البريد الإلكتروني',
    'bookingModal.emailPlaceholder': 'you@example.com',
    'bookingModal.mobile': 'رقم الجوال',
    'bookingModal.mobilePlaceholder': '+964 XXX XXX XXXX',
    'bookingModal.required': '*',
    'bookingModal.serviceSelectionTitle': 'اختيار الخدمة',
    'bookingModal.serviceType': 'اختر نوع الترجمة',
    'bookingModal.serviceTypePlaceholder': 'اختر نوع الخدمة',
    'bookingModal.simultaneousService': 'الترجمة الفورية - يوم عمل كامل: من 2 إلى 8 ساعات',
    'bookingModal.consecutiveService': 'الترجمة التتبعية',
    'bookingModal.onlineService': 'الترجمة عبر الإنترنت',
    'bookingModal.notesLabel': 'الموقع، الوقت المفضل، وأي ملاحظات أخرى...',
    'bookingModal.notesPlaceholder': 'قدم تفاصيل حول الحدث والموقع ووقت البدء والمدة وأي متطلبات خاصة.',
    'bookingModal.calendarTitle': 'اختر التواريخ',
    'bookingModal.selectedDates': 'التواريخ المختارة:',
    'bookingModal.calendarLegend.selected': 'مختار',
    'bookingModal.calendarLegend.booked': 'محجوز',
    'bookingModal.calendarLegend.available': 'متاح',
    'bookingModal.cancel': 'إلغاء',
    'bookingModal.bookViaWhatsApp': 'احجز عبر الواتساب',
    'bookingModal.rating': 'التقييم:',
    'bookingModal.languages': 'اللغات:',
    'bookingModal.specialties': 'التخصصات:',
    'bookingModal.sworn': 'محلف',
    'bookingModal.validationError': 'يرجى ملء جميع الحقول المطلوبة واختيار تاريخ واحد على الأقل.',
    'bookingModal.whatsappMessage': 'مرحباً! أود حجز خدمات الترجمة مع {interpreterName}.\n\nالتفاصيل:\n- الخدمة: {serviceName} ({servicePrice})\n- التواريخ: {selectedDates}\n- العميل: {clientName}\n- الهاتف: {mobile}\n- البريد الإلكتروني: {email}\n{notes}\n\nأتطلع للعمل معك!',
    'bookingModal.additionalNotes': '\n- ملاحظات إضافية: {notes}',

    // Simultaneous Page
    'simultaneous.badge': 'خدمة احترافية',
    'simultaneous.title': 'الترجمة الفورية',
    'simultaneous.subtitle': 'خدمات ترجمة فورية للمؤتمرات والاجتماعات والفعاليات الكبرى مع مترجمين محترفين ومعدات حديثة.',
    'simultaneous.bookButton': 'احجز مترجم فوري',
    'simultaneous.benefit1.title': 'ترجمة في الوقت الفعلي',
    'simultaneous.benefit1.desc': 'ترجمة فورية بدون تأخير أو توقف في المحادثة',
    'simultaneous.benefit2.title': 'للمناسبات الكبيرة',
    'simultaneous.benefit2.desc': 'مثالية للمؤتمرات والندوات والاجتماعات الدولية',
    'simultaneous.benefit3.title': 'معدات احترافية',
    'simultaneous.benefit3.desc': 'أحدث المعدات الصوتية وكبائن عازلة للصوت',
    'simultaneous.how.title': 'آلية العمل',
    'simultaneous.how.step1': 'يعمل المترجمون المحترفون في كبائن عازلة للصوت',
    'simultaneous.how.step2': 'يتم تقديم الترجمة الفورية عبر سماعات الرأس',
    'simultaneous.how.step3': 'مناسبة للفعاليات والمؤتمرات متعددة اللغات',
    'simultaneous.cta.title': 'هل أنت مستعد لحجز مترجمك الفوري؟',
    'simultaneous.cta.button': 'ابدأ الآن',

    // Consecutive Page
    'consecutive.badge': 'خدمة محادثة',
    'consecutive.title': 'الترجمة التتبعية',
    'consecutive.subtitle': 'ترجمة تعتمد على توقف المتحدث، مثالية لاجتماعات العمل والمشاورات القانونية والتجمعات الصغيرة التي يكون فيها تدفق المحادثة الطبيعي ضروريًا.',
    'consecutive.bookButton': 'احجز مترجم تتبعي',
    'consecutive.benefit1.title': 'تدفق طبيعي',
    'consecutive.benefit1.desc': 'يسمح بإيقاع محادثة طبيعي وتفاعل بين المتحدثين',
    'consecutive.benefit2.title': 'للمجموعات الصغيرة',
    'consecutive.benefit2.desc': 'مثالية لاجتماعات العمل والمفاوضات والاستشارات',
    'consecutive.benefit3.title': 'لمسة شخصية',
    'consecutive.benefit3.desc': 'تفاعل مباشر بين جميع الأطراف بوساطة احترافية',
    'consecutive.perfectFor.title': 'مثالية لـ',
    'consecutive.perfectFor.item1': 'مفاوضات واجتماعات العمل',
    'consecutive.perfectFor.item2': 'الاستشارات والإفادات القانونية',
    'consecutive.perfectFor.item3': 'المواعيد والاستشارات الطبية',
    'consecutive.perfectFor.item4': 'إجراءات وجلسات المحاكم',
    'consecutive.perfectFor.item5': 'الدورات التدريبية وورش العمل',
    'consecutive.perfectFor.item6': 'المقابلات والاستشارات الفردية',
    'consecutive.cta.title': 'هل تحتاج إلى مترجم تتبعي؟',
    'consecutive.cta.button': 'احجز جلستك',

    // Remote Page
    'remote.badge': 'خدمة افتراضية',
    'remote.title': 'الترجمة عن بعد',
    'remote.subtitle': 'خدمات ترجمة افتراضية تربط المترجمين والعملاء عبر أي مسافة. مثالية للاجتماعات عبر الإنترنت والندوات والمؤتمرات الرقمية.',
    'remote.bookButton': 'احجز مترجم عن بعد',
    'remote.benefit1.title': 'وصول عالمي',
    'remote.benefit1.desc': 'تواصل مع مترجمين من جميع أنحاء العالم من أي مكان',
    'remote.benefit2.title': 'متاح 24/7',
    'remote.benefit2.desc': 'خدمة على مدار الساعة عبر جميع المناطق الزمنية',
    'remote.benefit3.title': 'فعالة من حيث التكلفة',
    'remote.benefit3.desc': 'لا حاجة لتكاليف السفر أو متطلبات المكان',
    'remote.requirements.title': 'المتطلبات الفنية',
    'remote.requirements.basic.title': 'المتطلبات الأساسية',
    'remote.requirements.basic.item1': 'اتصال إنترنت مستقر (10 ميجابت في الثانية كحد أدنى)',
    'remote.requirements.basic.item2': 'جهاز كمبيوتر أو جهاز لوحي مع كاميرا وميكروفون',
    'remote.requirements.basic.item3': 'بيئة هادئة لصوت واضح',
    'remote.requirements.basic.item4': 'متصفح ويب أو تطبيق متوافق',
    'remote.requirements.platform.title': 'دعم المنصات',
    'remote.requirements.platform.item1': 'Zoom, Microsoft Teams, Google Meet',
    'remote.requirements.platform.item2': 'تكامل مع WebEx, GoToMeeting',
    'remote.requirements.platform.item3': 'منصات ترجمة مخصصة',
    'remote.requirements.platform.item4': 'الترجمة عبر الهاتف متاحة',
    'remote.cta.title': 'هل أنت مستعد للترجمة الافتراضية؟',
    'remote.cta.button': 'ابدأ جلسة عن بعد',

    // Translation Page
    'translation.badge': 'خدمة الترجمة التحريرية',
    'translation.title': 'ترجمة المستندات',
    'translation.subtitle': 'خدمات ترجمة مستندات احترافية مع مترجمين معتمدين. ترجمة سريعة ودقيقة وسرية لجميع احتياجات عملك وقانونك.',
    'translation.bookButton': 'احصل على عرض سعر للترجمة',
    'translation.service1.title': 'المستندات القانونية',
    'translation.service1.desc': 'العقود ووثائق المحاكم والمراسلات القانونية',
    'translation.service2.title': 'الترجمات المعتمدة',
    'translation.service2.desc': 'ترجمات رسمية مع شهادة للاستخدام القانوني',
    'translation.service3.title': 'سرية وآمنة',
    'translation.service3.desc': 'بروتوكولات سرية صارمة للوثائق الحساسة',
    'translation.types.title': 'أنواع المستندات التي نتعامل معها',
    'translation.types.item1': 'العقود والاتفاقيات القانونية',
    'translation.types.item2': 'السجلات والتقارير الطبية',
    'translation.types.item3': 'النصوص الأكاديمية والشهادات',
    'translation.types.item4': 'وثائق ونماذج الهجرة',
    'translation.types.item5': 'الكتيبات والمواصفات الفنية',
    'translation.types.item6': 'البيانات والتقارير المالية',
    'translation.types.item7': 'المواد التسويقية والمواقع الإلكترونية',
    'translation.types.item8': 'الوثائق الشخصية (شهادات الميلاد، إلخ)',
    'translation.turnaround.title': 'إنجاز سريع',
    'translation.turnaround.item1': '• خدمة سريعة: 24-48 ساعة',
    'translation.turnaround.item2': '• خدمة قياسية: 3-5 أيام عمل',
    'translation.turnaround.item3': '• المستندات الكبيرة: جدول زمني مخصص',
    'translation.turnaround.item4': '• تتوفر وظائف مستعجلة مقابل رسوم إضافية',
    'translation.process.title': 'عملية سهلة',
    'translation.process.item1': '• تحميل المستندات بشكل آمن عبر الإنترنت',
    'translation.process.item2': '• احصل على عرض أسعار فوري وجدول زمني',
    'translation.process.item3': '• ترجمة احترافية من قبل خبراء',
    'translation.process.item4': '• مراجعة الجودة والتسليم',
    'translation.cta.title': 'هل تحتاج إلى ترجمة مستندات؟',
    'translation.cta.button': 'قم بتحميل المستندات الآن',

    // About Page
    'about.badge': 'عن بوك لينغو',
    'about.title': 'كسر حواجز اللغة في جميع أنحاء العالم',
    'about.subtitle': 'تأسست بهدف جعل خدمات الترجمة الاحترافية متاحة للجميع، تربط بوك لينغو العملاء بمترجمين معتمدين في جميع أنحاء العالم.',
    'about.stat.clients': 'عملاء راضون',
    'about.stat.interpreters': 'مترجمون فوريون محترفون',
    'about.stat.languages': 'لغات مدعومة',
    'about.stat.reliability': 'مترجمون محلفون',
    'about.story.title': 'قصتنا',
    'about.story.p1': 'وُلدت بوك لينغو من رؤية بسيطة لكنها قوية: إزالة حواجز اللغة التي تمنع التواصل الهادف في عالمنا المترابط بشكل متزايد.',
    'about.story.p2': 'تأسست على يد فريق من محترفي اللغة ومبتكري التكنولوجيا، أدركنا الحاجة المتزايدة لخدمات ترجمة موثوقة واحترافية يمكنها التكيف مع مشهد الأعمال الحديث.',
    'about.story.p3': 'اليوم، نفخر بخدمة آلاف العملاء في جميع أنحاء العالم، من الشركات متعددة الجنسيات إلى رواد الأعمال الأفراد، ومساعدتهم على التواصل بفعالية عبر اللغات والثقافات.',
    'about.values.title': 'قيمنا',
    'about.value1.title': 'التميز',
    'about.value1.desc': 'نحافظ على أعلى المعايير في خدمات الترجمة من خلال الفحص الدقيق والتدريب المستمر.',
    'about.value2.title': 'الثقة',
    'about.value2.desc': 'بناء علاقات دائمة مع العملاء والمترجمين من خلال الشفافية والموثوقية.',
    'about.value3.title': 'الابتكار',
    'about.value3.desc': 'الاستفادة من التكنولوجيا لجعل خدمات الترجمة الاحترافية أكثر سهولة في الوصول إليها في جميع أنحاء العالم.',
    'about.mission.title': 'مهمتنا',
    'about.mission.desc': 'تمكين التواصل العالمي من خلال توفير خدمات ترجمة سهلة الوصول وموثوقة واحترافية تسد الفجوات اللغوية وتعزز التفاهم عبر الثقافات، مما يمكّن الشركات والأفراد من الازدهار في عالمنا المترابط.',
    'about.cta.title': 'هل أنت مستعد لتجربة الترجمة الاحترافية؟',
    'about.cta.button': 'ابدأ اليوم',

    // Pricing Page
    'pricing.badge': 'تسعير شفاف',
    'pricing.title': 'اختر خطة الترجمة الخاصة بك',
    'pricing.subtitle': 'خدمات ترجمة احترافية بأسعار شفافة. لا توجد رسوم خفية، لا مفاجآت - فقط خدمة استثنائية بأسعار عادلة.',
    'pricing.plan.basic.name': 'الأساسية',
    'pricing.plan.basic.desc': 'مثالية للاجتماعات الصغيرة والمشاورات',
    'pricing.plan.basic.feature1': 'ترجمة تتبعية',
    'pricing.plan.basic.feature2': 'حتى ساعتين لكل جلسة',
    'pricing.plan.basic.feature3': 'دعم عبر الهاتف والفيديو',
    'pricing.plan.basic.feature4': 'الحجز قبل 24 ساعة',
    'pricing.plan.basic.feature5': 'أزواج لغات أساسية',
    'pricing.plan.basic.button': 'اتصل بالمبيعات',
    'pricing.plan.pro.name': 'الاحترافية',
    'pricing.plan.pro.desc': 'مثالية لاجتماعات العمل والمؤتمرات',
    'pricing.plan.pro.feature1': 'فورية وتتبعية',
    'pricing.plan.pro.feature2': 'مدة جلسة ممتدة',
    'pricing.plan.pro.feature3': 'تشمل المعدات الاحترافية',
    'pricing.plan.pro.feature4': 'الحجز في نفس اليوم متاح',
    'pricing.plan.pro.feature5': '+50 زوج لغات',
    'pricing.plan.pro.feature6': 'مدير حساب مخصص',
    'pricing.plan.pro.badge': 'الأكثر شيوعًا',
    'pricing.plan.pro.button': 'اتصل بالمبيعات',
    'pricing.plan.enterprise.name': 'المؤسسات',
    'pricing.plan.enterprise.desc': 'حلول مصممة خصيصًا للمؤسسات الكبيرة',
    'pricing.plan.enterprise.feature1': 'جميع خدمات الترجمة',
    'pricing.plan.enterprise.feature2': 'مدة جلسة غير محدودة',
    'pricing.plan.enterprise.feature3': 'إعداد المعدات في الموقع',
    'pricing.plan.enterprise.feature4': 'حجز طارئ (إشعار قبل ساعتين)',
    'pricing.plan.enterprise.feature5': 'جميع اللغات مدعومة',
    'pricing.plan.enterprise.feature6': 'تعيين فريق مخصص',
    'pricing.plan.enterprise.feature7': 'خصومات على الحجم',
    'pricing.plan.enterprise.feature8': 'دعم ذو أولوية 24/7',
    'pricing.plan.enterprise.badge': 'أفضل قيمة',
    'pricing.plan.enterprise.button': 'اتصل بالمبيعات',
    'pricing.additional.title': 'خدمات إضافية',
    'pricing.additional.subtitle': 'عزز تجربة الترجمة الخاصة بك مع خدماتنا التكميلية',
    'pricing.additional.service1.name': 'ترجمة المستندات',
    'pricing.additional.service1.feature1': 'ترجمات معتمدة',
    'pricing.additional.service1.feature2': 'إنجاز خلال 24-48 ساعة',
    'pricing.additional.service1.feature3': 'دعم المستندات القانونية',
    'pricing.additional.service2.name': 'تأجير المعدات',
    'pricing.additional.service2.feature1': 'سماعات رأس لاسلكية',
    'pricing.additional.service2.feature2': 'كبائن المترجمين',
    'pricing.additional.service2.feature3': 'أنظمة صوتية',
    'pricing.additional.service3.name': 'دعم الإعداد عن بعد',
    'pricing.additional.service3.feature1': 'مساعدة فنية',
    'pricing.additional.service3.feature2': 'تكامل المنصة',
    'pricing.additional.service3.feature3': 'جلسة اختبار',
    'pricing.cta.title': 'هل أنت مستعد للبدء؟',
    'pricing.cta.subtitle': 'احجز جلستك الأولى للترجمة واستمتع بخدمة احترافية بأسعار تنافسية.',
    'pricing.cta.button': 'احجز الآن',

    // Contact Page
    'contact.title': 'أرسل لنا رسالة',
    'contact.subtitle': 'املأ النموذج أدناه وسنعاود الاتصال بك قريبًا.',
    'contact.name.label': 'الاسم الكامل',
    'contact.name.placeholder': 'جون دو',
    'contact.email.label': 'عنوان البريد الإلكتروني',
    'contact.email.placeholder': 'john@company.com',
    'contact.phone.label': 'رقم الهاتف',
    'contact.phone.placeholder': '+1 (555) 123-4567',
    'contact.subject.label': 'الموضوع',
    'contact.subject.placeholder': 'استفسار عن خدمات الترجمة',
    'contact.message.label': 'الرسالة',
    'contact.message.placeholder': 'أخبرنا عن احتياجات الترجمة الخاصة بك، تفاصيل الحدث، اللغات المطلوبة، إلخ.',
    'contact.button': 'إرسال الرسالة',
    'contact.alert': 'شكرًا لك على رسالتك! سنعاود الاتصال بك في غضون 24 ساعة.',

    // Interpreter Public Profile Page
    'interpreterProfile.bookTitle': 'احجز هذا المترجم',
    'interpreterProfile.bookSubtitle': 'أكمل النموذج لإرسال طلب حجز عبر الواتساب.',
    'interpreterProfile.clientName': 'الاسم الكامل للعميل/الشركة',
    'interpreterProfile.clientNamePlaceholder': 'اسمك أو اسم شركتك',
    'interpreterProfile.mobile': 'رقم الجوال',
    'interpreterProfile.mobilePlaceholder': 'مثال: 07801234567',
    'interpreterProfile.email': 'البريد الإلكتروني',
    'interpreterProfile.emailPlaceholder': 'you@example.com',
    'interpreterProfile.type': 'نوع الترجمة',
    'interpreterProfile.simultaneousOption': 'فورية - 300,000 دينار عراقي/ساعة',
    'interpreterProfile.consecutiveOption': 'تتبعية - 250,000 دينار عراقي/ساعة',
    'interpreterProfile.date': 'اختر التاريخ',
    'interpreterProfile.datePlaceholder': 'اختر تاريخًا',
    'interpreterProfile.notes': 'الموقع / الوقت / ملاحظات',
    'interpreterProfile.notesPlaceholder': 'قدم تفاصيل حول الحدث والموقع ووقت البدء والمدة وأي متطلبات خاصة.',
    'interpreterProfile.bookButton': 'احجز عبر الواتساب',
    'interpreterProfile.aboutTitle': 'عن المترجم',
    'interpreterProfile.experience': 'من الخبرة',
    'interpreterProfile.viewCv': 'عرض السيرة الذاتية',
    'interpreterProfile.galleryTitle': 'معرض الأعمال',
    'interpreterProfile.recommendationsTitle': 'خطابات توصية',
    'interpreterProfile.paymentTitle': 'الدفع',
    'interpreterProfile.paymentDesc': 'يتم الدفع نقدًا بالدينار العراقي مباشرة إلى المترجم بعد تقديم الخدمة.',
  }
};

const LanguageContext = createContext(null);

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState(() => {
    // On initial load, check localStorage for a saved language, otherwise default to 'en'
    if (typeof window !== 'undefined') {
        return localStorage.getItem('booklingo-lang') || 'en';
    }
    return 'en';
  });

  const toggleLanguage = () => {
    setLanguage(prevLang => (prevLang === 'en' ? 'ar' : 'en'));
  };

  useEffect(() => {
    // This effect runs whenever the language state changes
    // 1. Update localStorage with the new language
    if (typeof window !== 'undefined') {
        localStorage.setItem('booklingo-lang', language);
    }
    // 2. Update the document's direction and lang attributes for CSS and accessibility
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);
  
  const t = useCallback((key, replacements = {}) => {
    let translation = translations[language][key] || key;
    for (const placeholder in replacements) {
      translation = translation.replace(`{${placeholder}}`, replacements[placeholder]);
    }
    return translation;
  }, [language]);

  const value = {
    language,
    setLanguage,
    toggleLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
